language: go

go:
- 1.10.x

env:
  global:
  - MONGO_URL=mongodb://travis:test@127.0.0.1:27017/mydb_test

services:
- mongodb

before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
- go test -v -race -coverprofile=coverage.txt -covermode=atomic -tags=integration ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
